print()
print("\t\t\t\t\t\t\tREPLACE WORD APP")
print("\t\t\t\t\t=========================================================")
sentence = input("\t\t\t\t\t\tEnter the sentence\n: ")
print("\t\t\t\t\t=========================================================")
replace = input("\t\t\t\t\t\tEnter the replace word\n: ")
print("\t\t\t\t\t=========================================================")
new_Word = input("\t\t\t\t\t\tEnter new word: ")
print("\t\t\t\t\t=========================================================")

New_Sentence = sentence.replace(replace, new_Word)
print("\t\t\t\t\t=========================================================")
print("\t\t\t\t\t\tSentence: " + (New_Sentence))
print("\t\t\t\t\t=========================================================")